name: Go-Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: 1.22
    
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false  # Enabling default cache for Go

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

# Note: This configuration file uses a matrix strategy for Go versions.
# It sets up caching for Go modules to speed up builds and uses the latest versions of actions.
